schema:
  ${NEXT_PUBLIC_GRAPHQL_URI}:
    headers:
      authorization: Bearer ${TOKEN}
documents: "**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: .cache
typeInjectEntrypoint: graphql-let.d.ts
