query blocks($input: BlocksInput!) {
  blocks(input: $input) {
    totalCount
    edges {
      cursor
      node {
        id
        testId
        userId
        index
        markdown
      }
    }
  }
}
